#if MC_VERSION >= 11300

entity.2=experience_orb
entity.14=ender_pearl
entity.15=eye_of_ender
entity.17=experience_bottle
entity.22=firework_rocket
entity.24=spectral_arrow
entity.26=dragon_fireball
entity.41=boat biomesoplenty:boat
entity.200=end_crystal
entity.7000=lightning_bolt
entity.7001=wind_charge breeze_wind_charge
entity.7003=player

#ifdef IS_IRIS
entity.7002=entity_shadow
#endif

#endif
